name = "PHT"
description = "The PHT website theme"
homepage = "//github.com/providencehealthtech/pht-website-theme"
min_version = 0.15

[author]
    name = "robertdown"
    homepage = "//github.com/providencehealthtech"
